# 去同质化v2配置文件

# 时间衰减常数（小时）
decay_tau_hours: 6

# 热度子权重系数
coef_hot:
  article: 3.0           # total_articles_24h权重
  src_imp: 1.5           # source_importance权重
  wgt: 1.0               # ER wgt权重
  likes: 1.0             # likes权重（默认为0，可增量）
  rts: 2.0               # retweets权重（默认为0，可增量）

# 维度混合权重（总和=1）
mix_weight:
  hot: 0.55              # 热度权重
  rep: 0.25              # 代表性权重
  sent: 0.20             # 情感权重

# 聚类参数
clustering:
  n_clusters: 150        # 聚类数量
  min_cluster_size: 3    # 最小聚类大小
  max_cluster_size: 50   # 最大聚类大小（超过此值会细分）

# 打分阈值
scoring:
  min_score: 0.6         # 最低入选分数
  top_k: 100             # 入选数量上限

# EventRegistry参数
eventregistry:
  max_articles_per_event: 100  # 每个事件最大文章数
  min_event_weight: 1          # 最小事件权重 