# EventRegistry API 配额管理配置
quota_management:
  # 配额阈值设置
  thresholds:
    critical_low: 5      # 临界低配额，需要立即停止
    low: 20             # 低配额，发出警告
    warning: 50         # 警告阈值
    
  # 安全设置
  safety:
    min_quota_before_run: 10  # 运行前最小配额要求
    reserve_quota: 5          # 保留配额，避免完全耗尽
    
  # 监控设置
  monitoring:
    enable_alerts: true       # 启用配额告警
    alert_channels:           # 告警渠道
      - log                   # 日志告警
      - email                 # 邮件告警（如果配置）
    
  # 自动调整设置
  auto_adjust:
    enable: true              # 启用自动调整
    reduce_volume_on_low: true  # 配额低时自动减少请求量
    scaling_factors:
      low_quota: 0.5         # 低配额时减少50%请求量
      critical_low: 0.25     # 临界低配额时减少75%请求量

# API Key 轮换设置
key_rotation:
  enable: true               # 启用API Key轮换
  max_retries_per_key: 3    # 每个Key最大重试次数
  backoff_delay: 60         # 重试间隔（秒）
  
# 错误处理设置
error_handling:
  quota_exhausted:
    action: "stop"           # 配额耗尽时的动作：stop/retry/continue
    retry_delay: 3600       # 重试延迟（秒）
  rate_limit:
    action: "backoff"        # 限速时的动作：backoff/retry/stop
    backoff_multiplier: 2   # 退避倍数
